# main settings
runs: 1000
shots: 1
a_resolution: 16
a_step: 1
alpha: 0.05
epsilons: [1e-5, 9e-6, 8e-6, 7e-6, 6e-6, 5e-6, 4e-6, 3e-6, 2e-6, 1e-6]
# epsilons: [1e-2, 1e-3, 1e-4, 1e-5, 1e-6]
confint_method: all

# other
noise: 0.05
simulator: classical
